FROM python:3.12-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Ensure the output is unbuffered
ENV PYTHONUNBUFFERED=1


EXPOSE 5000
EXPOSE 8883

CMD ["python", "app.py"]
